name: Release
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 14.x
          registry-url: 'https://registry.npmjs.org'
          cache: yarn
      - run: yarn install
      - run: yarn run build
      - run: yarn test
        env:
          CI: true
      - uses: codecov/codecov-action@v2
      - uses: GoogleCloudPlatform/release-please-action@v2.28
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
      - if: ${{ steps.release.outputs.release_created }}
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
